### ISSUE TITLE
Incorrect label on terminator PCB

### ISSUE THREAD

**Issue by AaronJackson** [NF6X/RL02-USB#1]
Hi, great project.

Is the label for the for the 2x20 pin header on the terminator PCB design incorrect? 

Thanks

**Comment by NF6X** [comment]
Not that I am aware of. Why do you ask?

**Comment by AaronJackson** [comment]
It refers to TE_5102321-9 which only has 30 pins from what I can tell. It probably doesn't matter but I thought I would mention it.

**Comment by NF6X** [comment]
I don't see where you are finding only 30 pins. I believe that it's a 40 pin connector:

https://www.digikey.com/products/en?keywords=5102321-9

**Comment by AaronJackson** [comment]
Ah, my mistake. I was looking at the datasheet and counted only 30, but it shared across the entire range of TE_5102321. The -9 does have 40 pins. Sorry about that.

**Comment by NF6X** [comment]
No problem.

Just so you know, I have not assembled this board yet. I will probably resume work on the project in the next Retrochallenge round.
